### ISSUE TITLE
a NPE with coap_context_t

### ISSUE THREAD

**Issue by HypericumKaia** [obgm/libcoap#1302]
## Environment

- Build System:             Make
- Operating System:         Linux
- Operating System Version: Ubuntu 22.04 linux-6.2.16
- Hosted Environment:       None

## libcoap Configuration Summary

Copy all the "libcoap Configuration Summary:" output lines (about 40 lines) here after running
`./configure` (with any options that you have specified)
  or
`cmake ..` (with any -D options that you have specified)
  or if neither of the above two methods is used (do from within the libcoap directory)
`git describe --tags`

```
libcoap Configuration Summary:
      libcoap package version        : "4.3.4"
      libcoap package source         : "v4.3.4-44-ga3ed4665"
      libcoap API version            : "3"
      libcoap ABI version            : "3.1.1"
      libcoap libtool SO version     : "4.1.1"
      libcoap DTLS lib extn          : "-gnutls"
      host system                    : "x86_64-pc-linux-gnu"
      build with server support      : "yes"
      build with client support      : "yes"
      build with IPv4 support        : "yes"
      build with IPv6 support        : "yes"
      build with Unix socket support : "yes"
      build with TCP support         : "yes"
      build DTLS support             : "yes"
          -->  GnuTLS around         : "yes" (found GnuTLS 3.7.3)
               GNUTLS_CFLAGS         : "-I/usr/include/p11-kit-1"
               GNUTLS_LIBS           : "-lgnutls"
      add default names              : "yes"
      build Observe Persist          : "yes"
      build using epoll              : "yes"
      enable small stack size        : "no"
      enable separate responses      : "yes"
      enable OSCORE support          : "yes"
      enable Q-Block support         : "yes"
      enable max logging level       : "none"
      enable thread safe code        : "yes"
      enable recursive lock check    : "yes"
      build doxygen pages            : "no"
      build man pages                : "no"
      build unit test binary         : "no"
      build examples                 : "yes"
      install examples source        : "yes"
      build with gcov support        : "no"
      build shared library           : "no"
      build static library           : "yes"
```

## Problem Description

// Detailed problem description goes here.

a NPE during access coap_context_t

```
src/coap_threadsafe.c:297:3: runtime error: member access within null pointer of type 'coap_context_t' (aka 'struct coap_context_t')
    #0 0x6c0226 in coap_delete_resource /root/coap/src/coap_threadsafe.c:297:3
    #1 0x4e5b05 in hnd_delete /root/coap/examples/coap-server.c:1230:3
    #2 0x5eb39b in handle_request /root/coap/src/coap_net.c:3222:3
    #3 0x5cdf11 in coap_dispatch /root/coap/src/coap_net.c:3888:7
    #4 0x5c9059 in coap_read_session /root/coap/src/coap_net.c:1933:15
    #5 0x5da1e8 in coap_io_do_epoll_locked /root/coap/src/coap_net.c:2215:13
    #6 0x5a43bd in coap_io_process_with_fds_locked /root/coap/src/coap_io.c:1720:5
    #7 0x6c2107 in coap_io_process /root/coap/src/coap_threadsafe.c:563:9
    #8 0x4d653f in main /root/coap/examples/coap-server.c:3040:20
    #9 0x7fabd835bd8f  (/lib/x86_64-linux-gnu/libc.so.6+0x29d8f)
    #10 0x7fabd835be3f in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x29e3f)
    #11 0x422a94 in _start (/root/coap/examples/coap-server+0x422a94)

SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior src/coap_threadsafe.c:297:3 in 
```

### Expected Behavior

// Describe what you are expecting.

### Actual Behavior

// Describe what you are seeing.

### Steps to reproduce

1. step1
2. ...

### Code to reproduce this issue

```cpp
// the code should be wrapped in the ```cpp tag so that it will be displayed
better.
#include "coap3/coap.h"

void main()
{

}

```
// If your code is longer than 30 lines, upload it as an attachment.  Do not
include code that is proprietary or sensitive for your project.  Try to reduce
your code as much as possible so that it only demonstrates the issue.

## Debug Logs

see attachment
[crash.zip](https://github.com/obgm/libcoap/files/13712059/crash.zip)

```
Debug verbose logs go here.
Please copy the plain text here for us to search the error log. Or attach the
complete logs but leave the main part here if the log is *too* long.
```

## Other items if possible

- [ ] Does what you are trying to do work under any configuration.  Detail what
works.
- [ ] Network configuration that is not straightforward. Detail any networking
that may have NAT or firewalls that might affect what is going on.

**Comment by mrdeep1** [comment]
Thanks for raising this issue.  Please test out fix #1303 (waiting for merge into develop branch) and confirm (or not) this fixes the found issue.
