### ISSUE TITLE
Heap out-of-bounds read found by address sanitizer

### ISSUE THREAD

**Issue by bshastry** [obgm/libcoap#199]
Hi,

Here is a heap out-of-bounds found by ASan:

```
$ xxd build/out/libcoap/crash-dbbace6451955388c64e1e60cb23b8760d146b1f 
00000000: 405b 5b5b 5b5b 5b5b 5b5b 5b5b 5b5b 5b00  @[[[[[[[[[[[[[[.
00000010: 0000 0000 0000 0000 0000 005b 5be0 e0e0  ...........[[...
00000020: e0e0 e0e0 e0e0 e0e0 e0e0 e0e0 e0e0 e0e0  ................
00000030: e0e0 e0e0 e0e0 e0e0 e0e0 e0e0 0100 0000  ................
00000040: 0000 0000 e0c0 e0e0 e0e0 e0e0 e0e0 e0e0  ................
00000050: e0e0 e0e0 e0e0 e0e0 e4e0 e0e0 e0e0 e0e0  ................
00000060: e0e0 e0e0 e0e0 e0e0 e05b 5b5b 5b5b 5b5b  .........[[[[[[[
00000070: 5b5b 5b5b 5b5b 5b5b 5b5b 5b5b 5b5b 5b5b  [[[[[[[[[[[[[[[[
00000080: 5b5b 5b5b 5b5b 5b5b 5b5b 5b5b 5b5b 5b5b  [[[[[[[[[[[[[[[[
00000090: 5b5b 5b5b 5b5b 5b5b 5b5b 5b5b 5b5b 5b5b  [[[[[[[[[[[[[[[[
000000a0: 5b5b 5b5b 5b5b 5b5b 5b5b 5b5b 5b5b 5b5b  [[[[[[[[[[[[[[[[
000000b0: 5b5b 5b5b 5b5b 5b5b 5b5b 5b5b 5b5b 5b5b  [[[[[[[[[[[[[[[[
000000c0: 5b5b 5b5b 5b5b 5be0 e0e0 e0e0 e0e0 e0e0  [[[[[[[.........
000000d0: e0e0 e0e0 e0e0 e0e0 e0e0 e0e0 e0e0 e0e0  ................
000000e0: e0e0 e0e0 e0e0 0100 0000 0000 0000 e0e0  ................
000000f0: e0e0 e0e0 e0e0 e0e0 e0e0 e0e0 e0e0 e0e0  ................
00000100: e0e0 e0e0 e0

$ ./build/out/libcoap/pdu_parse_standalone build/out/libcoap/crash-dbbace6451955388c64e1e60cb23b8760

d146b1f 
StandaloneFuzzTargetMain: running 1 inputs
Running: build/out/libcoap/crash-dbbace6451955388c64e1e60cb23b8760d146b1f
=================================================================
==6747==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x612000000447 at pc 0x00000054512a bp 0x7ffea15489f0 sp 0x7ffea15489e8
READ of size 1 at 0x612000000447 thread T0
    #0 0x545129 in coap_opt_parse /src/libcoap/src/option.c:67:22
    #1 0x52e6e3 in next_option_safe /src/libcoap/src/pdu.c:403:13
    #2 0x52e121 in coap_pdu_parse_opt /src/libcoap/src/pdu.c:521:13
    #3 0x52ea30 in coap_pdu_parse /src/libcoap/src/pdu.c:565:47
    #4 0x52b6a7 in LLVMFuzzerTestOneInput /src/pdu_parse_target.c:8:5
    #5 0x52b9cb in main /src/libfuzzer/standalone/StandaloneFuzzTargetMain.c:37:5
    #6 0x7f8a5f01682f in __libc_start_main /build/glibc-Cl5G7W/glibc-2.23/csu/../csu/libc-start.c:291
    #7 0x41afb8 in _start (/home/bhargava/work/github/oss-fuzz/build/out/libcoap/pdu_parse_standalone+0x41afb8)

0x612000000447 is located 0 bytes to the right of 263-byte region [0x612000000340,0x612000000447)
allocated by thread T0 here:
    #0 0x4e929e in realloc /src/llvm/projects/compiler-rt/lib/asan/asan_malloc_linux.cc:117
    #1 0x52c427 in coap_pdu_resize /src/libcoap/src/pdu.c:169:25
    #2 0x52e97b in coap_pdu_parse /src/libcoap/src/pdu.c:560:8
    #3 0x52b6a7 in LLVMFuzzerTestOneInput /src/pdu_parse_target.c:8:5
    #4 0x52b9cb in main /src/libfuzzer/standalone/StandaloneFuzzTargetMain.c:37:5
    #5 0x7f8a5f01682f in __libc_start_main /build/glibc-Cl5G7W/glibc-2.23/csu/../csu/libc-start.c:291

SUMMARY: AddressSanitizer: heap-buffer-overflow /src/libcoap/src/option.c:67:22 in coap_opt_parse
Shadow bytes around the buggy address:
  0x0c247fff8030: fa fa fa fa fa fa fa fa fd fd fd fd fd fd fd fd
  0x0c247fff8040: fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd
  0x0c247fff8050: fd fd fd fd fd fd fd fd fd fa fa fa fa fa fa fa
  0x0c247fff8060: fa fa fa fa fa fa fa fa 00 00 00 00 00 00 00 00
  0x0c247fff8070: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
=>0x0c247fff8080: 00 00 00 00 00 00 00 00[07]fa fa fa fa fa fa fa
  0x0c247fff8090: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c247fff80a0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c247fff80b0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c247fff80c0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c247fff80d0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07 
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
  Shadow gap:              cc
==6747==ABORTING
```
I cannot attach files so I have shown a binary dump using `xxd`

**Comment by obgm** [comment]
Quick question: You are fuzzing the development HEAD, correct?

**Comment by mrdeep1** [comment]
Looks like it - I can reproduce it with valgrind and the binary data input.

**Comment by bshastry** [comment]
Of course. It would be nice if you could credit me for integrating libcoap into oss fuzz ;-)

**Comment by obgm** [comment]
Absolutely!

**Comment by mrdeep1** [comment]
@bshastry Now that #200 has been merged into the devlop branch, can you please confirm whether your issue is fixed or not?

**Comment by obgm** [comment]
Closing as ClusterFuzz reports testcase 5676475918319616 as fixed in [issue 8796](https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=8796).
