### ISSUE TITLE
Out of bounds read in coap_split_path

### ISSUE THREAD

**Issue by bshastry** [obgm/libcoap#212]
I am in the process of writing a new fuzzer test for oss-fuzz that fuzzes the data supplied to coap_split_path. Here is what I found for a URI like so:

```
coap://p://
```

```
=================================================================
==1==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x6030000486e1 at pc 0x00000053328e bp 0x7ffe11602680 sp 0x7ffe11602678
READ of size 1 at 0x6030000486e1 thread T0
    #0 0x53328d in dots /src/libcoap/src/uri.c:336:10
    #1 0x53138e in coap_split_path_impl /src/libcoap/src/uri.c:372:8
    #2 0x53110b in coap_split_path /src/libcoap/src/uri.c:404:3
    #3 0x52fd65 in LLVMFuzzerTestOneInput /src/split_path_target.c:15:5
    #4 0x58918c in fuzzer::Fuzzer::ExecuteCallback(unsigned char const*, unsigned long) /src/libfuzzer/FuzzerLoop.cpp:526:13
    #5 0x58777f in fuzzer::Fuzzer::RunOne(unsigned char const*, unsigned long, bool, fuzzer::InputInfo*, bool*) /src/libfuzzer/FuzzerLoo
p.cpp:451:3
    #6 0x58abdf in fuzzer::Fuzzer::MutateAndTestOne() /src/libfuzzer/FuzzerLoop.cpp:657:19
    #7 0x58daa6 in fuzzer::Fuzzer::Loop(std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<c
har> >, fuzzer::fuzzer_allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&) /src/
libfuzzer/FuzzerLoop.cpp:788:5
    #8 0x56c4e8 in fuzzer::FuzzerDriver(int*, char***, int (*)(unsigned char const*, unsigned long)) /src/libfuzzer/FuzzerDriver.cpp:758
:6
    #9 0x55f95c in main /src/libfuzzer/FuzzerMain.cpp:20:10
    #10 0x7f96cd28a82f in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x2082f)
    #11 0x41d008 in _start (/out/split_path_fuzzer+0x41d008)

0x6030000486e1 is located 0 bytes to the right of 17-byte region [0x6030000486d0,0x6030000486e1)
allocated by thread T0 here:
    #0 0x52b9a8 in operator new[](unsigned long) /src/llvm/projects/compiler-rt/lib/asan/asan_new_delete.cc:109
    #1 0x588f98 in fuzzer::Fuzzer::ExecuteCallback(unsigned char const*, unsigned long) /src/libfuzzer/FuzzerLoop.cpp:517:23
    #2 0x58777f in fuzzer::Fuzzer::RunOne(unsigned char const*, unsigned long, bool, fuzzer::InputInfo*, bool*) /src/libfuzzer/FuzzerLoo
p.cpp:451:3
    #3 0x58abdf in fuzzer::Fuzzer::MutateAndTestOne() /src/libfuzzer/FuzzerLoop.cpp:657:19
    #4 0x58daa6 in fuzzer::Fuzzer::Loop(std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<c
har> >, fuzzer::fuzzer_allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&) /src/
libfuzzer/FuzzerLoop.cpp:788:5
    #5 0x56c4e8 in fuzzer::FuzzerDriver(int*, char***, int (*)(unsigned char const*, unsigned long)) /src/libfuzzer/FuzzerDriver.cpp:758
:6
    #6 0x55f95c in main /src/libfuzzer/FuzzerMain.cpp:20:10
    #7 0x7f96cd28a82f in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x2082f)

SUMMARY: AddressSanitizer: heap-buffer-overflow /src/libcoap/src/uri.c:336:10 in dots
```

**Comment by mrdeep1** [comment]
I'm not able to reproduce this using valgrind.  I can see where it may be happening in the code, but need to be able to prove that this is down to how the compiler builds the object code.

Are you sure that you have provided the correct exact URI including any binary data to parse?

**Comment by bshastry** [comment]
Sorry, here's the right string:

```
bhargava@x230:~/work/github/oss-fuzz$ xxd build/out/libcoap/crash-751c367f48b8b817e905ba19b21f26baa3cc93ce                              
00000000: 636f 6170 3a2f 2f86 636f 6170 3a2f 2f    coap://.coap://
```

**Comment by mrdeep1** [comment]
@obgm I believe that this one can be closed now.
