### ISSUE TITLE
Out of bounds read in coap_show_pdu()

### ISSUE THREAD

**Issue by bshastry** [obgm/libcoap#214]
Hi,

I found the following OOB read while fuzzing the coap_show_pdu() API with a PDU parsed from the following (hex) payload

```
bhargava@x230:~/work/github/oss-fuzz$ xxd build/out/libcoap/crash-356f5975d59b65a39b7c845002147eaa73b29545 
00000000: 5a0a 5b5b                                Z.[[
```

```
=================================================================
==15==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x602000000d1a at pc 0x000000530f04 bp 0x7ffe947b1c70 sp 0x7ffe947b1c68
READ of size 1 at 0x602000000d1a thread T0
    #0 0x530f03 in coap_show_pdu /src/libcoap/src/debug.c:450:36
    #1 0x52fcab in LLVMFuzzerTestOneInput /src/pdu_parse_target.c:33:5
    #2 0x58901c in fuzzer::Fuzzer::ExecuteCallback(unsigned char const*, unsigned long) /src/libfuzzer/FuzzerLoop.cpp:526:13
    #3 0x58760f in fuzzer::Fuzzer::RunOne(unsigned char const*, unsigned long, bool, fuzzer::InputInfo*, bool*) /src/libfuzzer/FuzzerLo$
p.cpp:451:3
    #4 0x58aa6f in fuzzer::Fuzzer::MutateAndTestOne() /src/libfuzzer/FuzzerLoop.cpp:657:19
    #5 0x58d936 in fuzzer::Fuzzer::Loop(std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<$
har> >, fuzzer::fuzzer_allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&) /src$
libfuzzer/FuzzerLoop.cpp:788:5
    #6 0x56c378 in fuzzer::FuzzerDriver(int*, char***, int (*)(unsigned char const*, unsigned long)) /src/libfuzzer/FuzzerDriver.cpp:75$
:6
    #7 0x55f7ec in main /src/libfuzzer/FuzzerMain.cpp:20:10
    #8 0x7fc60bb6082f in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x2082f)
    #9 0x41d008 in _start (/out/pdu_parse_fuzzer+0x41d008)

0x602000000d1a is located 0 bytes to the right of 10-byte region [0x602000000d10,0x602000000d1a)
allocated by thread T0 here:
    #0 0x4ebecf in malloc /src/llvm/projects/compiler-rt/lib/asan/asan_malloc_linux.cc:146
    #1 0x535bec in coap_pdu_init /src/libcoap/src/pdu.c:116:9
    #2 0x52fc35 in LLVMFuzzerTestOneInput /src/pdu_parse_target.c:23:23
    #3 0x58901c in fuzzer::Fuzzer::ExecuteCallback(unsigned char const*, unsigned long) /src/libfuzzer/FuzzerLoop.cpp:526:13
    #4 0x58760f in fuzzer::Fuzzer::RunOne(unsigned char const*, unsigned long, bool, fuzzer::InputInfo*, bool*) /src/libfuzzer/FuzzerLo$
p.cpp:451:3
    #5 0x58aa6f in fuzzer::Fuzzer::MutateAndTestOne() /src/libfuzzer/FuzzerLoop.cpp:657:19
    #6 0x58d936 in fuzzer::Fuzzer::Loop(std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<$
har> >, fuzzer::fuzzer_allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&) /src$
libfuzzer/FuzzerLoop.cpp:788:5
    #7 0x56c378 in fuzzer::FuzzerDriver(int*, char***, int (*)(unsigned char const*, unsigned long)) /src/libfuzzer/FuzzerDriver.cpp:75$
:6
    #8 0x55f7ec in main /src/libfuzzer/FuzzerMain.cpp:20:10
    #9 0x7fc60bb6082f in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x2082f)

SUMMARY: AddressSanitizer: heap-buffer-overflow /src/libcoap/src/debug.c:450:36 in coap_show_pdu
```

**Comment by mrdeep1** [comment]
Thanks for this.  Issue is reproducible and will be worked on.

**Comment by mrdeep1** [comment]
@obgm I believe that this one can be closed now.
